// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMhgkMqZj5JfOxf9T5qDA-At4ScFUiUeg',
    appId: '1:721669628431:web:f2f970d3ac7706e584397a',
    messagingSenderId: '721669628431',
    projectId: 'finderucc-a082c',
    authDomain: 'finderucc-a082c.firebaseapp.com',
    storageBucket: 'finderucc-a082c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc9bzCBCnhKfudfV7eUTjxLeraeUjI60E',
    appId: '1:721669628431:android:04c996a3493c716e84397a',
    messagingSenderId: '721669628431',
    projectId: 'finderucc-a082c',
    storageBucket: 'finderucc-a082c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23KPB0KeKzGt0Vhwxmk2bu91BqgwE13Q',
    appId: '1:721669628431:ios:7562bb13d02fd55a84397a',
    messagingSenderId: '721669628431',
    projectId: 'finderucc-a082c',
    storageBucket: 'finderucc-a082c.appspot.com',
    iosBundleId: 'com.example.finderucc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23KPB0KeKzGt0Vhwxmk2bu91BqgwE13Q',
    appId: '1:721669628431:ios:7562bb13d02fd55a84397a',
    messagingSenderId: '721669628431',
    projectId: 'finderucc-a082c',
    storageBucket: 'finderucc-a082c.appspot.com',
    iosBundleId: 'com.example.finderucc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMhgkMqZj5JfOxf9T5qDA-At4ScFUiUeg',
    appId: '1:721669628431:web:f12deb451f97c96e84397a',
    messagingSenderId: '721669628431',
    projectId: 'finderucc-a082c',
    authDomain: 'finderucc-a082c.firebaseapp.com',
    storageBucket: 'finderucc-a082c.appspot.com',
  );
}
